### ISSUE TITLE
OrderedModelQuerySet doesn't respect order_with_respect_to.

### ISSUE THREAD

**Issue by caspervk** [bfirsh/django-ordered-model#201]
Using the new `bulk_create()`, the order of the new objects starts at the maximum value of all objects, whereas it should only consider objects with the same values in the `order_with_respect_to` fields.

**Comment by imomaliev** [comment]
@caspervk Hi, could you check on new version, it should be fixed now

**Comment by caspervk** [comment]
It's still an issue for me.

Deleting all `bulk_create` code in `ordered_model/models.py` and manually doing `Apple.objects.bulk_create(Apple(basket=basket, order=i, **a) for i, a in enumerate(apples))` works, but leaving the new `bulk_create` code and doing `Apple.objects.bulk_create(Apple(basket=basket, **a) for a in apples)` doesn't create any apples.

**Comment by danielholmes** [comment]
I'm also getting this error. During a `formset.save()` within django admin. I'm a bit short on time right now to look into it, but in case it helps here's my stack trace:

```
Traceback (most recent call last):
  File "/myapp/tests/test_admin.py", line 54, in test_create
    "month_prices-1-price_idr": "10000",
  File "/pylib/python3.7/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/pylib/python3.7/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/pylib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/pylib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/pylib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/pylib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/pylib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/pylib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/pylib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/pylib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/pylib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/pylib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 1562, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/myapp/admin.py", line 68, in save_related
    super(HealthCoverAdmin, self).save_related(request, form, formsets, change)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 1116, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/pylib/python3.7/site-packages/django/contrib/admin/options.py", line 1104, in save_formset
    formset.save()
  File "/pylib/python3.7/site-packages/django/forms/models.py", line 669, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/pylib/python3.7/site-packages/django/forms/models.py", line 807, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/pylib/python3.7/site-packages/django/forms/models.py", line 947, in save_new
    return super().save_new(form, commit=commit)
  File "/pylib/python3.7/site-packages/django/forms/models.py", line 646, in save_new
    return form.save(commit=commit)
  File "/pylib/python3.7/site-packages/django/forms/models.py", line 458, in save
    self.instance.save()
  File "/myapp/models.py", line 134, in save
    super(HealthCoverMonth, self).save(*args, **kwargs)
  File "/pylib/python3.7/site-packages/ordered_model/models.py", line 203, in save
    order = self.get_ordering_queryset().get_next_order()
  File "/pylib/python3.7/site-packages/ordered_model/models.py", line 186, in get_ordering_queryset
    return qs.filter_by_order_with_respect_to(self)
AttributeError: 'QuerySet' object has no attribute 'filter_by_order_with_respect_to'
```

**Comment by imomaliev** [comment]
@danielholmes You need to set new custom Manager class `OrderedModelManager`

**Comment by imomaliev** [comment]
@caspervk could you help me track down your issue?

**Comment by caspervk** [comment]
@imomaliev I unsuccessfully tried to isolate the bug in a unittest, so it looks like it works 😄 Sorry for the confusion, and thank you for your work.

**Comment by madEng84** [comment]
@imomaliev
I have this error upgrading to a new version (>=3.2) of this package

There should be written in the documentation that if a custom Manager or QuerySet is used, it should override from OrderedModelManager or from OrderedModelQuerySet.

It is not clear to me if this exception occurs only when a custom manager is used for a model that uses order_with_respect_to variable

**Comment by littlehome-eugene** [comment]
It is happening because of the following lines

 ```
   def get_ordering_queryset(self, qs=None):
        qs = qs or self._meta.default_manager.all()
        return qs.filter_by_order_with_respect_to(self)
```

if you have own manager/queryset or qs won't have `filter_by_order_with_respect_to`

So you have to currently subclass orderedmodel manager/queryset

**Comment by shuckc** [comment]
We mention the need to call our custom `ModelManager` quite clearly now https://github.com/bfirsh/django-ordered-model#custom-manager-and-queryset and of course you add additional filters to the resulting QuerySet as usual.
