### ISSUE TITLE
Admin up/down links don't seem to work with order_with_respect_to

### ISSUE THREAD

**Issue by bfirsh** [bfirsh/django-ordered-model#97]
As noted in https://github.com/bfirsh/django-ordered-model/commit/20bf5ebbbaa30a7bda3bb379c3302c500f5d4919#commitcomment-18368306

There are now tests for the admin interface, so first step is probably writing some tests for the admin with order_with_respect_to...

**Comment by archatas** [comment]
I don't have enough time to write a correct patch at the moment, but I figured out what is necessary to make admin interface work for the inlines. You have to modify the `OrderedTabularInline` class and add these corrected methods:

    @classmethod
    def get_urls(cls, model_admin):
        def wrap(view):
            def wrapper(*args, **kwargs):
                return model_admin.admin_site.admin_view(view)(*args, **kwargs)
            return update_wrapper(wrapper, view)
        return [
            url(r'^([^/]+)/{model}/([^/]+)/move-(up)/$'.format(**cls.get_model_info()), wrap(cls.move_view),
                name='{app}_{model}_order_up_inline'.format(**cls.get_model_info())),
            url(r'^([^/]+)/{model}/([^/]+)/move-(down)/$'.format(**cls.get_model_info()), wrap(cls.move_view),
                name='{app}_{model}_order_down_inline'.format(**cls.get_model_info())),
        ]

    @classmethod
    def get_model_info(cls):
        return {
            'app': cls.model._meta.app_label,
            'model': cls.model._meta.model_name,
        }

    def move_up_down_links(self, obj):
        if not obj._state.adding:
            order_obj_name = 'obj'
            if obj._get_order_with_respect_to() is not None:
                order_obj_name = str(obj._get_order_with_respect_to()[0][1].id)
            return render_to_string("ordered_model/admin/order_controls.html", {
                'app_label': self.model._meta.app_label,
                'model_name': self.model._meta.model_name,
                'module_name': self.model._meta.model_name, # backwards compat
                'object_id': obj.id,
                'urls': {
                    'up': reverse("admin:{app}_{model}_order_up_inline".format(
                        admin_name=self.admin_site.name, **self.get_model_info()),
                        args=[order_obj_name, obj.id, 'up']),
                    'down': reverse("admin:{app}_{model}_order_down_inline".format(
                        admin_name=self.admin_site.name, **self.get_model_info()),
                        args=[order_obj_name, obj.id, 'down']),
                },
                'query_string': self.request_query_string
            })
        return ""
    move_up_down_links.allow_tags = True
    move_up_down_links.short_description = _(u'Move')

This code supports custom primary keys (e.g. UUID fields).

**Comment by rmertens** [comment]
I'm also encountering this problem. 

-  Is the code above the suggested fix? 
- Is there any chance that it could be incorporated? If you want I can make a PR with it, even though I don't understand the internals.

**Comment by derek-adair** [comment]
I ran into this problem when I changed the primary key of the ordered field to something custom.

`myfield = models.IntegerField(primary_key=True, editable=False)`

I still need to nail down the exact reason it broke but I believe it had something to do with this.  Removing the primary_key=True and reseting my DB did the trick.

**Comment by shuckc** [comment]
Looks like another case of #127 so may be fixed in today's 1.4.2  release

**Comment by shuckc** [comment]
Assuming this is now fixed, so closing.

**Comment by remort** [comment]
Seems still broken for me.
I have OneToMany models:

```
MODELS.PY:

class Message(OrderedModel):
    lesson = models.ForeignKey(Lesson, related_name='messages', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Message text', blank=True)

    order_with_respect_to = 'lesson'

    class Meta(OrderedModel.Meta):
        pass



class Lesson(models.Model):
    title = models.CharField(max_length=255)


ADMIN.PY:

@admin.register(lesson.Lesson)
class LessonAdmin(OrderedInlineModelAdminMixin, admin.ModelAdmin):
    class MessageAdmin(OrderedTabularInline):
        model = message.Message
        extra = 1
        fields = ('text', 'move_up_down_links')
        readonly_fields = ('move_up_down_links',)
        ordering = ('order',)

    inlines = [MessageAdmin]
    list_display = ('title',)
```

Move Up/Down links appears in inline form for Message objects, but doesn't work. Interchange `OrderedTabularInline` with `OrderedStackedInline` has no effect.
What I'm doing wrong ?
